// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Yt9Qx1YMYINBTpDq1xCwwPJaWuYB_B0',
    appId: '1:369294205767:web:2d7e99cf14e8c522f72262',
    messagingSenderId: '369294205767',
    projectId: 'clarity-75c9c',
    authDomain: 'clarity-75c9c.firebaseapp.com',
    storageBucket: 'clarity-75c9c.firebasestorage.app',
    measurementId: 'G-RTBJ9KG8LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVpCNfAWTQIsEoybMogFglAH0ATuQUvWw',
    appId: '1:369294205767:android:2d1ab9502754e5fef72262',
    messagingSenderId: '369294205767',
    projectId: 'clarity-75c9c',
    storageBucket: 'clarity-75c9c.firebasestorage.app',
  );
}
